openapi: 3.0.3
info:
  description: Microservice for accessing player data via REST API
  title: Player Data Service API
  version: 1.0.0
servers:
- url: http://localhost:8080
paths:
  /api/players:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Player'
                type: array
          description: A list of players
      summary: Retrieve all players
      x-accepts: application/json
  /api/players/{playerID}:
    get:
      parameters:
      - explode: false
        in: path
        name: playerID
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Player'
          description: A single player
      summary: Retrieve a single player by ID
      x-accepts: application/json
components:
  schemas:
    Player:
      example:
        name: name
        id: 0
        team: team
        age: 6
      properties:
        id:
          description: The player's ID
          format: int64
          type: integer
        name:
          description: The player's name
          type: string
        age:
          description: The player's age
          type: integer
        team:
          description: The player's team
          type: string
      required:
      - age
      - id
      - name
      - team
      type: object

