openapi: 3.0.3
info:
    title: Player Data Service API
    description: Microservice for accessing player data via REST API
    version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /api/players:
    get:
      summary: Retrieve all players
      responses:
        '200':
          description: A list of players
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Player'
  /api/players/{playerID}:
    get:
      summary: Retrieve a single player by ID
      parameters:
        - in: path
          name: playerID
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: A single player
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Player'
components:
  schemas:
    Player:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: The player's ID
        name:
          type: string
          description: The player's name
        age:
          type: integer
          description: The player's age
        team:
          type: string
          description: The player's team
      required:
        - id
        - name
        - age
        - team
  
